Thesis/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Thesis.Areas.HelpPage.ModelDescriptions;
using Thesis.Areas.HelpPage.Models;

namespace Thesis.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

Thesis/Controllers/SpasController.cs
using System.Web.Mvc;

namespace Thesis.Controllers
{
    public class SpasController : Controller
    {
        public ActionResult Angular()
        {
            return View();
        }

        public ActionResult Ember()
        {
            return View();
        }

        public ActionResult React()
        {
            return View();
        }

        public ActionResult Backbone()
        {
            return View();
        }

        public ActionResult Commonjs()
        {
            return View();
        }

        public PartialViewResult Partial(string name)
        {
            return PartialView("AngularTemplates/" + name);
        }
    }
}

Thesis/Views/Shared/_GoogleStatistics.cshtml
<div class="well">
    <h1>Keywords: "Two way bindings"</h1>
    <script type="text/javascript" src="//www.google.com/trends/embed.js?hl=en-US&q=two+way+binding&cmpt=q&tz&tz&content=1&cid=TIMESERIES_GRAPH_0&export=5&w=500&h=330"></script>
    <script type="text/javascript" src="//www.google.com/trends/embed.js?hl=en-US&q=two+way+binding&cmpt=q&tz&tz&content=1&cid=GEO_TABLE_0_0&export=5&w=500&h=330"></script>
</div>

<div class="well">
    <h1>Keywords: "Angular js"</h1>
    <script type="text/javascript" src="//www.google.com/trends/embed.js?hl=en-US&q=angular+js&cmpt=q&tz&tz&content=1&cid=TIMESERIES_GRAPH_0&export=5&w=500&h=330"></script>
    <script type="text/javascript" src="//www.google.com/trends/embed.js?hl=en-US&q=angular+js&cmpt=q&tz&tz&content=1&cid=GEO_TABLE_0_0&export=5&w=500&h=330"></script>
</div>

<div class="well">
    <h1>Keywords: "Ember js"</h1>
    <script type="text/javascript" src="//www.google.com/trends/embed.js?hl=en-US&q=ember+js&cmpt=q&tz&tz&content=1&cid=TIMESERIES_GRAPH_0&export=5&w=500&h=330"></script>
    <script type="text/javascript" src="//www.google.com/trends/embed.js?hl=en-US&q=ember+js&cmpt=q&tz&tz&content=1&cid=GEO_TABLE_0_0&export=5&w=500&h=330"></script>
</div>

<div class="well">
    <h1>Keywords: "React js"</h1>
    <script type="text/javascript" src="//www.google.com/trends/embed.js?hl=en-US&q=react+js&cmpt=q&tz&tz&content=1&cid=TIMESERIES_GRAPH_0&export=5&w=500&h=330"></script>
    <script type="text/javascript" src="//www.google.com/trends/embed.js?hl=en-US&q=react+js&cmpt=q&tz&tz&content=1&cid=GEO_TABLE_0_0&export=5&w=500&h=330"></script>
</div>


<div class="well">
    <h1>Keywords: "Backbone js"</h1>
    <script type="text/javascript" src="//www.google.com/trends/embed.js?hl=en-US&q=backbone+js&cmpt=q&tz&tz&content=1&cid=TIMESERIES_GRAPH_0&export=5&w=500&h=330"></script>
    <script type="text/javascript" src="//www.google.com/trends/embed.js?hl=en-US&q=backbone+js&cmpt=q&tz&tz&content=1&cid=GEO_TABLE_0_0&export=5&w=500&h=330"></script>
</div>

Thesis/Views/Shared/_JsLibrarySelection.cshtml
<div class="well">
    <div class="row">
        <div class="col col-md-3 col-sm-6">
            <div class="row">
                <a href='@Url.Action("Angular", "Spas")' class="btn btn-default">
                    <img src='@Url.Content("~/Content/Images/Angular.jpg")' class="index-img" />
                </a>
            </div>
        </div>
        <div class="col col-md-3 col-sm-6">
            <a href='@Url.Action("Ember", "Spas")' class="btn btn-default">
                <img src='@Url.Content("~/Content/Images/Ember.png")' class="index-img" />
            </a>
        </div>
        <div class="col col-md-3 col-sm-6">
            <a href='@Url.Action("Commonjs", "Spas")' class="btn btn-default">
                <img src='@Url.Content("~/Content/Images/React.png")' class="index-img" />
            </a> 
        </div>
        <div class="col col-md-3 col-sm-6">
            <a href='@Url.Action("Backbone", "Spas")' class="btn btn-default">
                <img src='@Url.Content("~/Content/Images/Backbone.png")' class="index-img" />
            </a>
        </div>
    </div>
</div>

Thesis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
</head>
<body>
    @Html.Partial("_navbar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - JavaScript framework comparison</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Thesis/Views/Shared/_LayoutSimple.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
</head>
<body>
<div>
    @Html.Partial("_navbar")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <div class="container">
        @RenderBody()
    </div>
</div>
</body>
</html>

Thesis/Views/Shared/_LayoutTesting.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width"/>
    <title>@ViewBag.Title</title>
    @RenderSection("styles", required: false)
</head>
<body>
<h1>Welcome to testing</h1>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - JavaScript framework comparison</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

Thesis/Views/Shared/_navbar.cshtml
@using Microsoft.Ajax.Utilities
@functions
{
    private string ShowActive(string viewbag)
    {
        return viewbag.IsNullOrWhiteSpace() ? string.Empty : "active";
    }
}
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("JavaScript frameworks", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="@ShowActive(ViewBag.Home)">@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                <li class="dropdown @ShowActive(ViewBag.JsFrameworks)">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">JS frameworks <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>@Html.ActionLink("Angular", "Angular", "Spas", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Ember", "Ember", "Spas", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("React", "Commonjs", "Spas", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Backbone", "Backbone", "Spas", new { area = "" }, null)</li>
                    </ul>
                </li>
                <li class="@ShowActive(ViewBag.Api)">@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                <li class="@ShowActive(ViewBag.About)">@Html.ActionLink("Google Statistics", "About", "Home", new {area = ""}, null)</li>
            </ul>
        </div>
    </div>
</div>